### ISSUE TITLE
support renamed dependencies

### ISSUE THREAD

**Issue by tedbyron** [Riey/cargo-feature#27]
When using the [package](https://doc.rust-lang.org/stable/cargo/reference/specifying-dependencies.html#renaming-dependencies-in-cargotoml) key with dependencies, `cargo-feature` doesn't do anything and exits silently with successfull exit code. 

Example
```toml
[dependencies]
neovim = { version = "0.4.0", package = "nvim-rs" }
```

If I add a feature with the package name: `cargo feature nvim-rs +use_tokio`, there is no output, Cargo.toml doesn't change.

If I add a feature with the alias name: `cargo feature neovim +use_tokio`, I get the error "Can't find package from metadata! please check package `neovim` is exists in manifest".
